before_install:
  - sudo apt-get install -y libev4
  - sudo curl -L -o /usr/local/lib/zenoh-0.3.0-SNAPSHOT.jar https://atolab.github.io/atobin/zenoh-java/latest/ubuntu/16.04/zenoh-0.3.0-SNAPSHOT.jar
  
language: java
